version: '3'
services:
  db:
    image: library/postgres:10-alpine
    container_name: postgres
    network_mode: host
    volumes:
      - postgres:/var/lib/postgresql/data
    restart: always
    environment:
      - POSTGRES_DB=monopoly
      - POSTGRES_PASSWORD=dev
  monopoly:
    build:
      context: ../
      dockerfile: ./docker-build/Dockerfile
    ports:
      - "8081:8080"
    container_name: monopoly
    restart: unless-stopped
volumes:
  postgres:
    driver: local